// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PF6_Team4_Alkiviadis.Data;

namespace PF6_Team4_Alkiviadis.Migrations
{
    [DbContext(typeof(PF6_Team4_DbContext_Alkiviadis))]
    partial class PF6_Team4_DbContext_AlkiviadisModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PF6_Team4_Alkiviadis.Models.BackerRewardPackage", b =>
                {
                    b.Property<int>("BackerRewardPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RewardPackageId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BackerRewardPackageId");

                    b.HasIndex("RewardPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("BackerRewardPackages");
                });

            modelBuilder.Entity("PF6_Team4_Alkiviadis.Models.BackerUserProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountDonated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("BackerUserProjects");
                });

            modelBuilder.Entity("PF6_Team4_Alkiviadis.Models.CreatorUserProject", b =>
                {
                    b.Property<int>("CreatorUserProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CreatorUserProjectId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("CreatorUserProjects");
                });

            modelBuilder.Entity("PF6_Team4_Alkiviadis.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PF6_Team4_Alkiviadis.Models.ProjectRewardPackage", b =>
                {
                    b.Property<int>("ProjectRewardPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("RewardPackageId")
                        .HasColumnType("int");

                    b.HasKey("ProjectRewardPackageId");

                    b.ToTable("ProjectRewardPackages");
                });

            modelBuilder.Entity("PF6_Team4_Alkiviadis.Models.RewardPackage", b =>
                {
                    b.Property<int>("RewardPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxAmountRoGetReward")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RewardDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RewardPackageId");

                    b.ToTable("RewardPackages");
                });

            modelBuilder.Entity("PF6_Team4_Alkiviadis.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PF6_Team4_Alkiviadis.Models.BackerRewardPackage", b =>
                {
                    b.HasOne("PF6_Team4_Alkiviadis.Models.RewardPackage", "rewardpackage")
                        .WithMany()
                        .HasForeignKey("RewardPackageId");

                    b.HasOne("PF6_Team4_Alkiviadis.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("rewardpackage");

                    b.Navigation("user");
                });

            modelBuilder.Entity("PF6_Team4_Alkiviadis.Models.BackerUserProject", b =>
                {
                    b.HasOne("PF6_Team4_Alkiviadis.Models.Project", "project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("PF6_Team4_Alkiviadis.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("PF6_Team4_Alkiviadis.Models.CreatorUserProject", b =>
                {
                    b.HasOne("PF6_Team4_Alkiviadis.Models.Project", "project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("PF6_Team4_Alkiviadis.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("project");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
